version: '3.8'
services: 
    toolbox-api:
      build: ./toolbox-api
      restart: unless-stopped
      env_file: ./.env
      ports:
        - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      environment:       
        - CLIENT_ORIGIN=$CLIENT_ORIGIN
      networks:
        - backend
        - frontend
    toolbox-ui:
      depends_on:
        - toolbox-api
      build:
        context: ./toolbox-ui
        args:
          - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
      ports:
        - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
      networks:
        - frontend  
networks:
  backend:
  frontend: